package com.mtanuri.t1113.operacao;

public enum OperacaoFilme {
	
	INSERIR, EXCLUIR, RENOMEAR, ATUALIZAR_DESCRICAO, LISTAR_TODOS, PESQUISAR_POR_NOME, 
	ADICIONAR_ATOR, REMOVER_ATOR, ADICIONAR_DIRETOR, REMOVER_DIRETOR

}
