package com.mtanuri.ada.t1113.view;

public enum Menu {

    NOVO_FILME, NOVO_ATOR, NOVO_DIRETOR, EDITAR_FILME, EDITAR_AUTOR, EDITAR_DIRETOR, PESQUISAR_FILME, PESQUISAR_AUTOR, PESQUISAR_DIRETOR, LISTAR_TODOS_FILMES, LISTAR_TODOS_ATORES, LISTAR_TODOS_DIRETORES


}
